### ISSUE TITLE
Missing redirects (Slash vs. non-slash)

### ISSUE THREAD

**Issue by helms-charity** [hlxsites/airlessco#124]
On the live site, extensionless pages (e.g: https://www.airlessco.com/emea/pl/products/accessories/revtipspraytips ) redirect to having a slash on the end (e.g: https://www.airlessco.com/emea/pl/products/accessories/revtipspraytips/).

Franklin has a mixed experience, where some pages only work without the slash (https://main--airlessco--hlxsites.hlx.page/na/en/products/mp455) and some only work with it (https://main--airlessco--hlxsites.hlx.page/na/en/products/)

**Comment by helms-charity** [comment]
Are these handled at the CDN? Let me know if I can help...

**Comment by bstopp** [comment]
This is a good point - the reason for it is the URLs with trailing slash are auto-loaded to the `index` file in the specified folder.

The ones without a trailing slash have existing pages. There's three options:

1) Ignore it and/or try to add redirects - this may be hard to achieve in a way that doesn't affect content.
2) Move every page into its own folder so that they're all "index" files - then every page ends in a trailing slash.
3) Move the landing pages to not be `index` type pages, so that they resolve without a trailing slash.

**Comment by bstopp** [comment]
Customer has opted for option 2. So we'll start moving the content around accordingly.

**Comment by bstopp** [comment]
All redirects have been uploaded to the file.
