### ISSUE TITLE
Contact Forms (multi-lingual)

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/airlessco#6]
https://www.airlessco.com/na/en/contactus/
https://www.airlessco.com/emea/de/contactus/

**Comment by dkuntze** [comment]
styling like this:
https://www.graco.com/us/en/homeowner/forms/paint-case-form.html

**Comment by helms-charity** [comment]
To do:
- Check with customer if "salutation" is needed? It does not appear on the English form. If needed, we need translations. For now, I've used an mdash in between "yes" and the rest of the sentence. [ask customer]

- @dkuntze  to check with his form developer contact to find out how to escape commas within cells [update: just leave the dashes for now]

- Check with customer if the 3 dashes as a non-selectable placeholder is OK for dropdown selections. If not, we need a translation for "Select one". We can't leave a blank space (and it shouldn't be blank, since it is not a field you can put text in).

- I suggest removing placeholder text ("E.g. Buzz") because "E.g." is not translated, and there are no placeholders in the original forms. (also the examples may not make sense; there are 5 numbers for postal code but that doesn't work for Europe, and there's no telephone placeholder anyway.) [update: will remove all]

-  ask customer about the yes checkbox vs. yes or no radio buttons?
