### ISSUE TITLE
No Homepage Link

### ISSUE THREAD

**Issue by bstopp** [hlxsites/airlessco#68]
There's no place on the website that takes a visitor back to the homepage.

Shouldn't this exist?

**Comment by helms-charity** [comment]
It doesn't exist on the live site, but I agree I think it would be a nice feature. I think to do that, we'd want to make the logo a separate png on top of the background so that it could be linked?

(ignore my crude erasure of the dark grey).

![image](https://user-images.githubusercontent.com/3883795/218768646-1e2f53af-4f02-4af5-b0ab-432f244c7c80.png)

**Comment by angellg1** [comment]
could I provide you with a PNG logo file that could replace the embedded logo in the header?

**Comment by bstopp** [comment]
Yes, if you  have a new one, we can make that change.
